// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagementSystem.Models;

namespace RestaurantManagementSystem.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20200901134912_ReservationTable Create")]
    partial class ReservationTableCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("RestaurantManagementSystem.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReserveDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RestaurantTableTableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("RestaurantTableTableId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.RestaurantTable", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sits")
                        .HasColumnType("INTEGER");

                    b.HasKey("TableId");

                    b.ToTable("RestaurantTables");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Reservation", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.RestaurantTable", "RestaurantTable")
                        .WithMany()
                        .HasForeignKey("RestaurantTableTableId");
                });
#pragma warning restore 612, 618
        }
    }
}
